### ISSUE TITLE
Compile errors with v0.5.0-preview on Windows

### ISSUE THREAD

**Issue by adamski** [realm/realm-cpp#125]
After updating to 0.5.0 from 0.4.0 I get the following compilation errors:

```
cpprealm/experimental/managed_list.hpp(139): error C2143: syntax error: missing ';' before '<'
cpprealm/experimental/managed_list.hpp(143): note: see reference to class template instantiation 'realm::experimental::managed<std::vector<_Ty,std::allocator<_Ty>>,enable_if<is_primitive<T>::value,void>::type>' being compiled
cpprealm/experimental/managed_list.hpp(139): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
cpprealm/experimental/managed_list.hpp(139): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
cpprealm/experimental/managed_list.hpp(316): error C2143: syntax error: missing ';' before '<'
cpprealm/experimental/managed_list.hpp(343): note: see reference to class template instantiation 'realm::experimental::managed<std::vector<T*,std::allocator<T*>>,void>' being compiled
cpprealm/experimental/managed_list.hpp(316): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
cpprealm/experimental/managed_list.hpp(316): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
cpprealm/experimental/managed_list.hpp(323): error C2143: syntax error: missing ';' before '<'
cpprealm/experimental/managed_list.hpp(323): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
cpprealm/experimental/managed_list.hpp(323): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
cpprealm/experimental/managed_list.hpp(332): error C2143: syntax error: missing ';' before '<'
cpprealm/experimental/managed_list.hpp(332): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
cpprealm/experimental/managed_list.hpp(332): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
cpprealm/experimental/managed_list.hpp(338): error C2143: syntax error: missing ';' before '<'
cpprealm/experimental/managed_list.hpp(338): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
cpprealm/experimental/managed_list.hpp(338): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
[464/468] Building CXX object _deps\cpprealm-build\src\CMakeFiles\cpprealm.dir\cpprealm\internal\network\network_transport.cpp.obj
```

**Comment by leemaguire** [comment]
Hi @adamski, I can't reproduce on my side. Are you able to successfully build the Windows example [here](https://github.com/realm/realm-cpp/tree/main/examples/windows)? Can you also make sure you've added the necessary additions to your CMakeLists.txt file for when using MSVC (These can be seen in the example project.)

**Comment by adamski** [comment]
I'll try the example project. I can build 0.4.0, the errors only occur with 0.5.0.

**Comment by leemaguire** [comment]
@adamski make sure the git submodules are up to date. v0.5.0 bumped the Realm Core dependancy.

**Comment by adamski** [comment]
I'm using FetchContent / CPM so I assume that should take care of getting the correct submodules?

**Comment by adamski** [comment]
Switching the include order fixed the issue.

From 
```
#include <cpprealm/experimental/sdk.hpp>
#include <cpprealm/sdk.hpp>
```

to

```
#include <cpprealm/sdk.hpp>
#include <cpprealm/experimental/sdk.hpp>
```
